baseURL = "https://sltnmsyffa.github.io"
languageCode = "en-us"
title = "Sultan Tammam Musyaffa"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Sultan Tammam Musyaffa"
imageUrl = "https://avatars.githubusercontent.com/u/109848194"
imageTitle = "Sultan Tammam Musyaffa"
imageWidth = 165
imageHeight = 165

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/sltnmsyffa"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/itsprof"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/sltnTmsyffa"
